In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/pythonquestions/Answers.csv
/kaggle/input/pythonquestions/Questions.csv
/kaggle/input/pythonquestions/Tags.csv

In [3]:
df_tags = pd.read_csv('/kaggle/input/pythonquestions/Tags.csv')
df_tags

               Id        Tag
0             469     python
1             469        osx
2             469      fonts
3             469  photoshop
4             502     python
...           ...        ...
1885073  40143338     python
1885074  40143365     python
1885075  40143365      numpy
1885076  40143365     theano
1885077  40143365       nnet

[1885078 rows x 2 columns]

In [5]:
df_questions = pd.read_csv('/kaggle/input/pythonquestions/Questions.csv', encoding = 'ISO-8859-1')
df_questions

,Id,OwnerUserId,CreationDate,Score,Title,Body
0,469,147.0,2008-08-02T15:11:16Z,21,How can I find the full path to a font from it...,<p>I am using the Photoshop's javascript API t...
1,502,147.0,2008-08-02T17:01:58Z,27,Get a preview JPEG of a PDF on Windows?,<p>I have a cross-platform (Python) applicatio...
2,535,154.0,2008-08-02T18:43:54Z,40,Continuous Integration System for a Python Cod...,<p>I'm starting work on a hobby project with a...
3,594,116.0,2008-08-03T01:15:08Z,25,cx_Oracle: How do I iterate over a result set?,<p>There are several ways to iterate over a re...
4,683,199.0,2008-08-03T13:19:16Z,28,Using 'in' to match an attribute of Python obj...,<p>I don't remember whether I was dreaming or ...
...,...,...,...,...,...,...
607277,40143190,333403.0,2016-10-19T23:36:01Z,1,How to execute multiline python code from a ba...,<p>I need to extend a shell script (bash). As ...
607278,40143228,6662462.0,2016-10-19T23:40:00Z,0,How to get google reCaptcha image source using...,<p>I understood that reCaptcha loads a new fra...
607279,40143267,4064680.0,2016-10-19T23:44:07Z,0,Updating an ManyToMany field with Django rest,<p>I'm trying to set up this API so I can use ...
607280,40143338,7044980.0,2016-10-19T23:52:27Z,2,Most possible pairs,"<p>Given a list of values, and information on ..."
607281,40143365,4133131.0,2016-10-19T23:55:49Z,0,Theano operations returning odd results,<p>So I'm trying to learn how to use Theano an...

In [6]:
df_answers = pd.read_csv('/kaggle/input/pythonquestions/Answers.csv', encoding = 'ISO-8859-1')
df_answers

,Id,OwnerUserId,CreationDate,ParentId,Score,Body
0,497,50.0,2008-08-02T16:56:53Z,469,4,<p>open up a terminal (Applications-&gt;Utilit...
1,518,153.0,2008-08-02T17:42:28Z,469,2,<p>I haven't been able to find anything that d...
2,536,161.0,2008-08-02T18:49:07Z,502,9,<p>You can use ImageMagick's convert utility f...
3,538,156.0,2008-08-02T18:56:56Z,535,23,<p>One possibility is Hudson. It's written in...
4,541,157.0,2008-08-02T19:06:40Z,535,20,"<p>We run <a href=""http://buildbot.net/trac"">B..."
...,...,...,...,...,...,...
987117,40143290,3831.0,2016-10-19T23:46:58Z,40142906,0,<p>I am fairly certain your problem is your us...
987118,40143315,3125566.0,2016-10-19T23:49:43Z,40143166,2,"<p>First thing, you should use <code>if/elif</..."
987119,40143317,2350575.0,2016-10-19T23:50:04Z,40142194,0,<p>If you are using firefox ver >47.0.1 you ne...
987120,40143349,6934347.0,2016-10-19T23:54:02Z,40077010,0,<p>I solved my own problem defining the follow...
987121,40143370,6502500.0,2016-10-19T23:56:31Z,40142538,0,<p>I can't seem to reproduce your error but up...

In [7]:
tags_q = pd.merge(df_tags, df_questions, on='Id')
tags_q

,Id,Tag,OwnerUserId,CreationDate,Score,Title,Body
0,469,python,147.0,2008-08-02T15:11:16Z,21,How can I find the full path to a font from it...,<p>I am using the Photoshop's javascript API t...
1,469,osx,147.0,2008-08-02T15:11:16Z,21,How can I find the full path to a font from it...,<p>I am using the Photoshop's javascript API t...
2,469,fonts,147.0,2008-08-02T15:11:16Z,21,How can I find the full path to a font from it...,<p>I am using the Photoshop's javascript API t...
3,469,photoshop,147.0,2008-08-02T15:11:16Z,21,How can I find the full path to a font from it...,<p>I am using the Photoshop's javascript API t...
4,502,python,147.0,2008-08-02T17:01:58Z,27,Get a preview JPEG of a PDF on Windows?,<p>I have a cross-platform (Python) applicatio...
...,...,...,...,...,...,...,...
1885069,40143338,python,7044980.0,2016-10-19T23:52:27Z,2,Most possible pairs,"<p>Given a list of values, and information on ..."
1885070,40143365,python,4133131.0,2016-10-19T23:55:49Z,0,Theano operations returning odd results,<p>So I'm trying to learn how to use Theano an...
1885071,40143365,numpy,4133131.0,2016-10-19T23:55:49Z,0,Theano operations returning odd results,<p>So I'm trying to learn how to use Theano an...
1885072,40143365,theano,4133131.0,2016-10-19T23:55:49Z,0,Theano operations returning odd results,<p>So I'm trying to learn how to use Theano an...
1885073,40143365,nnet,4133131.0,2016-10-19T23:55:49Z,0,Theano operations returning odd results,<p>So I'm trying to learn how to use Theano an...

In [10]:
tag_counts = tags_q['Tag'].value_counts()
tag_counts.head(60)

Tag
python               607282
django                62818
python-2.7            34616
pandas                26854
python-3.x            26814
numpy                 25848
list                  18951
matplotlib            16521
regex                 14047
dictionary            13413
tkinter               10766
string                10616
flask                 10488
google-app-engine     10286
csv                    9323
arrays                 9170
json                   8023
mysql                  7529
linux                  7121
html                   7118
scipy                  6908
multithreading         6804
sqlalchemy             6661
windows                6267
beautifulsoup          6054
django-models          5797
javascript             5788
selenium               5654
xml                    5332
pyqt                   5217
class                  5083
osx                    5056
pygame                 5050
opencv                 4995
dataframe              4958
function               4867
c++                    4850
file                   4665
scrapy                 4638
sockets                4585
subprocess             4418
loops                  4355
scikit-learn           4289
pip                    4178
algorithm              4168
unicode                4135
parsing                4062
datetime               4040
web-scraping           3940
multiprocessing        3876
wxpython               3713
java                   3591
postgresql             3591
performance            3553
unit-testing           3535
for-loop               3505
sql                    3478
sorting                3381
qt                     3340
python-requests        3273
Name: count, dtype: int64

In [13]:
filtered_df = tags_q[tags_q['Tag'] == 'database']
df = filtered_df[:10]
df

,Id,Tag,OwnerUserId,CreationDate,Score,Title,Body
13,594,database,116.0,2008-08-03T01:15:08Z,25,cx_Oracle: How do I iterate over a result set?,<p>There are several ways to iterate over a re...
40,1734,database,59.0,2008-08-05T00:12:55Z,20,Any experiences with Protocol Buffers?,<p>I was just looking through some information...
166,20927,database,1914.0,2008-08-21T19:41:57Z,6,updating an auto_now DateTimeField in a parent...,<p>I've got two models: Message and Attachment...
650,60805,database,1448.0,2008-09-13T19:58:02Z,49,Getting random row through SQLAlchemy,<p>How do I select a(or some) random row(s) fr...
857,79850,database,10708.0,2008-09-17T04:02:53Z,17,How do you design data models for Bigtable/Dat...,<p>Since the Google App Engine Datastore is ba...
1264,116894,database,19031.0,2008-09-22T19:18:21Z,3,Best practices for manipulating database resul...,<p>I am writing a simple Python web applicatio...
1649,140026,database,12030.0,2008-09-26T14:56:05Z,5,Writing a Domain Specific Language for selecti...,<p>I'm writing a server that I expect to be ru...
2082,172066,database,25274.0,2008-10-05T14:29:56Z,1,Django UserProfile... without a password,<p>I'd like to create a subset of Users that d...
2213,181648,database,3355.0,2008-10-08T07:21:19Z,3,Problem opening berkeley db in python,<p>I have problems opening a berkeley db in py...
2225,182053,database,NaN,2008-10-08T10:29:28Z,3,Setup Python enviroment on windows,<p>How do I setup a Python enviroment on windo...

In [15]:
for index, row in df.iterrows():
    print(f"ID: {row['Id']}")
    print(row['Body'])
    print()

ID: 594
<p>There are several ways to iterate over a result set. What are the tradeoff of each?</p>


ID: 1734
<p>I was just looking through some information about Google's <a href="http://code.google.com/apis/protocolbuffers/">protocol buffers</a> data interchange format.  Has anyone played around with the code or even created a project around it?</p>

<p>I'm currently using XML in a Python project for structured content created by hand in a text editor, and I was wondering what the general opinion was on Protocol Buffers as a user-facing input format.  The speed and brevity benefits definitely seem to be there, but there are so many factors when it comes to actually generating and processing the data.</p>

ID: 20927
<p>I've got two models: Message and Attachment. Each attachment is attached to a specific message, using a ForeignKey on the Attachment model. Both models have an auto_now DateTimeField called updated. I'm trying to make it so that when any attachment is saved, it also sets the updated field on the associated message to now. Here's my code:</p>

<pre><code>def save(self):
    super(Attachment, self).save()
    self.message.updated = self.updated
</code></pre>

<p>Will this work, and if you can explain it to me, why? If not, how would I accomplish this?</p>


ID: 60805
<p>How do I select a(or some) random row(s) from a table using SQLAlchemy? </p>


ID: 79850
<p>Since the Google App Engine Datastore is based on <a href="http://research.google.com/archive/bigtable.html">Bigtable</a> and we know that's not a relational database, how do you design a <strong><em>database schema</em>/*data model*</strong> for applications that use this type of database system?</p>


ID: 116894
<p>I am writing a simple Python web application that consists of several pages of business data formatted for the iPhone. I'm comfortable programming Python, but I'm not very familiar with Python "idiom," especially regarding classes and objects. Python's object oriented design differs somewhat from other languages I've worked with. So, even though my application is working, I'm curious whether there is a better way to accomplish my goals.</p>

<p>Specifics: How does one typically implement the request-transform-render database workflow in Python? Currently, I am using pyodbc to fetch data, copying the results into attributes on an object, performing some calculations and merges using a list of these objects, then rendering the output from the list of objects. (Sample code below, SQL queries redacted.) Is this sane? Is there a better way? Are there any specific "gotchas" I've stumbled into in my relative ignorance of Python? I'm particularly concerned about how I've implemented the list of rows using the empty "Record" class.</p>

<pre><code>class Record(object):
    pass

def calculate_pnl(records, node_prices):
    for record in records:
        try:
            # fill RT and DA prices from the hash retrieved above
            if hasattr(record, 'sink') and record.sink:
                record.da = node_prices[record.sink][0] - node_prices[record.id][0]
                record.rt = node_prices[record.sink][1] - node_prices[record.id][1]
            else:
                record.da = node_prices[record.id][0]
                record.rt = node_prices[record.id][1]

            # calculate dependent values: RT-DA and PNL
            record.rtda = record.rt - record.da
            record.pnl = record.rtda * record.mw
        except:
            print sys.exc_info()

def map_rows(cursor, mappings, callback=None):
    records = []
    for row in cursor:
        record = Record()
        for field, attr in mappings.iteritems():
            setattr(record, attr, getattr(row, field, None))
        if not callback or callback(record):
            records.append(record)

    return records

def get_positions(cursor):
    # get the latest position time
    cursor.execute("SELECT latest data time")
    time = cursor.fetchone().time
    hour = eelib.util.get_hour_ending(time)

    # fetch the current positions
    cursor.execute("SELECT stuff FROM atable", (hour))

    # read the rows
    nodes = {}
    def record_callback(record):
        if abs(record.mw) &gt; 0:
            if record.id: nodes[record.id] = None
            return True
        else:
            return False
    records = util.map_rows(cursor, {
        'id': 'id',
        'name': 'name',
        'mw': 'mw'
    }, record_callback)

    # query prices
    for node_id in nodes:
        # RT price
        row = cursor.execute("SELECT price WHERE ? ? ?", (node_id, time, time)).fetchone()
        rt5 = row.lmp if row else None

        # DA price
        row = cursor.execute("SELECT price WHERE ? ? ?", (node_id, hour, hour)).fetchone()
        da = row.da_lmp if row else None

        # update the hash value
        nodes[node_id] = (da, rt5)

    # calculate the position pricing
    calculate_pnl(records, nodes)

    # sort
    records.sort(key=lambda r: r.name)

    # return the records
    return records
</code></pre>


ID: 140026
<p>I'm writing a server that I expect to be run by many different people, not all of whom I will have direct contact with. The servers will communicate with each other in a cluster. Part of the server's functionality involves selecting a small subset of rows from a potentially very large table. The exact choice of what rows are selected will need some tuning, and it's important that it's possible for the person running the cluster (eg, myself) to update the selection criteria without getting each and every server administrator to deploy a new version of the server.</p>

<p>Simply writing the function in Python isn't really an option, since nobody is going to want to install a server that downloads and executes arbitrary Python code at runtime.</p>

<p>What I need are suggestions on the simplest way to implement a Domain Specific Language to achieve this goal. The language needs to be capable of simple expression evaluation, as well as querying table indexes and iterating through the returned rows. Ease of writing and reading the language is secondary to ease of implementing it. I'd also prefer not to have to write an entire query optimiser, so something that explicitly specifies what indexes to query would be ideal.</p>

<p>The interface that this will have to compile against will be similar in capabilities to what the App Engine datastore exports: You can query for sequential ranges on any index on the table (eg, less-than, greater-than, range and equality queries), then filter the returned row by any boolean expression. You can also concatenate multiple independent result sets together.</p>

<p>I realise this question sounds a lot like I'm asking for SQL. However, I don't want to require that the datastore backing this data be a relational database, and I don't want the overhead of trying to reimplement SQL myself. I'm also dealing with only a single table with a known schema. Finally, no joins will be required. Something much simpler would be far preferable.</p>

<p>Edit: Expanded description to clear up some misconceptions.</p>


ID: 172066
<p>I'd like to create a subset of Users that don't have a login... basically as a way to add a photographer field to photos without having a full blown account associated with that person (since in many cases, they'll never actually log in to the site). A caveat is that I'd also like to be able to enable an account for them later.</p>

<p>So, I think the question becomes what's the best way to set up a "People" table that ties to the User table without actually extending the User table with UserProfile.</p>


ID: 181648
<p>I have problems opening a berkeley db in python using bdtables. As bdtables is used by the library I am using to access the database, I need it to work.</p>

<p>The problem seems to be that the db environment I am trying to open (I got a copy of the database to open), is version 4.4 while libdb is version 4.6. I get the following error using bsddb.dbtables.bsdTableDB([dbname],[folder]):</p>

<pre><code>(-30972, "DB_VERSION_MISMATCH: Database environment version mismatch -- Program version 4.6 doesn't match environment version 4.4")
</code></pre>

<p>However, bsddb.btopen([dbname]) works.</p>

<p>I have also tried installing db4.4-util, db4.5-util and db4.6-util. Trying to use db4.6_verify results in:</p>

<pre><code>db4.6_verify: Program version 4.6 doesn't match environment version 4.4
db4.6_verify: DB_ENV-&gt;open: DB_VERSION_MISMATCH: Database environment version mismatchs
</code></pre>

<p>db4.4_verify results in the computer just hanging, and nothing happening.</p>

<p>Finally, if I run db4.4_recover on the database, that works. However, afterwards I get the following error 'No such file or directory' in python.</p>


ID: 182053
<p>How do I setup a Python enviroment on windows computer so I can start writing and running Python scripts, is there an install bundle?  Also which database should i use?</p>

<p>Thanks</p>

<p><hr /></p>

<p>Sorry I should of mentioned that I am using this for web based applications. Does it require apache? or does it use another http server? What is the standard setup for Python running web apps?</p>

In [16]:
for index, row in df.iterrows():
    print(f"ID: {row['Id']}")
    print(row['Title'])
    print()

ID: 594
cx_Oracle: How do I iterate over a result set?

ID: 1734
Any experiences with Protocol Buffers?

ID: 20927
updating an auto_now DateTimeField in a parent model w/ Django

ID: 60805
Getting random row through SQLAlchemy

ID: 79850
How do you design data models for Bigtable/Datastore (GAE)?

ID: 116894
Best practices for manipulating database result sets in Python?

ID: 140026
Writing a Domain Specific Language for selecting rows from a table

ID: 172066
Django UserProfile... without a password

ID: 181648
Problem opening berkeley db in python

ID: 182053
Setup Python enviroment on windows